### ISSUE TITLE
Bad api call for FTX

### ISSUE THREAD

**Issue by MarkEhr** [OttoAllmendinger/gnome-shell-bitcoin-markets#104]
The FTX provider won't work cause it's calling `https://ftx.com/api/markets/BTC-USD` instead of `https://ftx.com/api/markets/BTC/USD`.
The dash is hardcoded so it should be fixed in the provider's code. Are you accepting PRs?

**Comment by OttoAllmendinger** [comment]
I am!

**Comment by OttoAllmendinger** [comment]
fixed
