### ISSUE TITLE
Provides no useful info, after install

### ISSUE THREAD

**Issue by axelsimon** [OttoAllmendinger/gnome-shell-bitcoin-markets#105]
After installing (in this case, turning on on extensions.gnome.org), the value of the default pair (BTC/USD, on Bitstamp) is not shown. Only an up or down triangle is displayed.

Trying to add another pair (XBT/EUR on Kraken) also goes nowhere, and there is no help or documentation as to how to set that up, either in the extension's menu or the README here.

The actual pair for Kraken is XXBTZEUR, but that's only part of the solution.
`{v} {qs}` shows nothing for either providers.

**Comment by OttoAllmendinger** [comment]
if you replace `{v} {qs}` with `abcd`, does it display `abcd` ?

**Comment by axelsimon** [comment]
Hi,
No, It doesn't.

**Comment by axelsimon** [comment]
This is with Gnome Shell 3.36.7 on Fedora 32.

**Comment by OttoAllmendinger** [comment]
Can you please also provide a screenshot of the indicator and your preferences?

**Comment by axelsimon** [comment]
Sure, here you go:
![Screenshot from 2021-01-22 14-46-46](https://user-images.githubusercontent.com/1172256/105505573-05c25f00-5cc1-11eb-8211-c22d189fd602.png)
![Screenshot from 2021-01-22 14-46-25](https://user-images.githubusercontent.com/1172256/105505576-05c25f00-5cc1-11eb-8b3a-6463d6fb7ad2.png)
![Screenshot from 2021-01-22 14-45-51](https://user-images.githubusercontent.com/1172256/105505577-065af580-5cc1-11eb-8efa-c5c4e05b89d4.png)

**Comment by OttoAllmendinger** [comment]
The screen looks very narrow, I suspect the text display is squeezed to the point that the number disappears entirely.

We can confirm this by disabling "Show Change" and removing one of the indicators (maybe temporarily disabling one of the other extensions)

If this turns out to be the issue I can explore other options to still show info when little space is available.
