### ISSUE TITLE
Request Rate

### ISSUE THREAD

**Issue by shaun-ba** [OttoAllmendinger/gnome-shell-bitcoin-markets#11]
Hi,

Can you please amend your code to reduce the request rate to bitcoinaverage.com .

We're getting  around a request per section from every user using this code, 1minute is plenty for the current free API.

If you want to debug more let me know!

**Comment by MatzFan** [comment]
Was getting 429 responses here too from BitcoinAverage, but re-selecting Provider in Settings seems to provide temporary workaround.

Could a user-defined API call interval setting be added to mitigate?

Awesome shell extension btw.

**Comment by OttoAllmendinger** [comment]
@MatzFan which version are you using? BitcoinAverage now has a ~15 minute polling limit (per-ip). The most recent version available on extensions.gnome.org should not show this behavior.

**Comment by MatzFan** [comment]
@OttoAllmendinger installed `metadata.json` says `"version": 33`. Not sure how to tell the release version from extensions.gnome.org (I'm a GNOME extension noob), but I installed it only a few days ago.

Would the API respect my SOCKS proxy by any chance - I see the following in your code [here](https://github.com/OttoAllmendinger/gnome-shell-bitcoin-markets/blob/master/src/HTTP.js#L71-L74)
```
Soup.Session.prototype.add_feature.call(
  _httpSession,
  new Soup.ProxyResolverDefault()
);
```
I run Tor, so if so perhaps that is causing rate limit to be hit sometimes. In which case I'll have to live with it. Thanks

**Comment by shaun-ba** [comment]
Depending on how worthwhile real-time data is to you, you could add the ability to use our API keys :-)

**Comment by GoodMirek** [comment]
If I set 4 different tickers on bitfinex, I hit rate limiting (HTTP status 429). Does the extension manage the interval between requests on per-ticker basis or globally?
Could it adaptively slow down if 429 is received?

**Comment by str** [comment]
Hi! I also get "Too many requests" error in Bitfinex.

![selection_015](https://user-images.githubusercontent.com/123817/35455720-a323a406-0298-11e8-9938-929a6cfc3c38.png)

**Comment by OttoAllmendinger** [comment]
The request limit is per-pair, so if you have three tickers you make 3x the requests

So right now I recommending increasing the interval in ProviderBitfinex.js as a workaround

I see that the v2 api allows retrieving ticker data for multiple pairs in a single request. I will implement that in the future.

**Comment by OttoAllmendinger** [comment]
new polling method should alleviate these problems to some extent
