### ISSUE TITLE
Gnome 40

### ISSUE THREAD

**Issue by yellowgh0st** [OttoAllmendinger/gnome-shell-bitcoin-markets#111]
Extension needs to be updated to work with Gnome 40 and GTK4.

**Comment by OttoAllmendinger** [comment]
You can try this branch https://github.com/OttoAllmendinger/gnome-shell-bitcoin-markets/tree/gnome40

Updated version is pending review in e.g.o store

**Comment by yellowgh0st** [comment]
Thanks! Will do test.

**Comment by yellowgh0st** [comment]
Looks it works as expected except:

1. Had to restart gnome-shell to make it available using `gnome-extensions list`
**2. Drag'n'Drop to reorder tickers doesn't work anymore.**

**Comment by OttoAllmendinger** [comment]
thanks for testing!

added #124
