### ISSUE TITLE
    ['(m|k|sat)v8', _('formatted value with 8 decimals')] formatting does not work

### ISSUE THREAD

**Issue by bigmalloy** [OttoAllmendinger/gnome-shell-bitcoin-markets#112]
Hi, Great  gnome extension, fantastic work.
While testing Bitcoin markets with the settings below everything works great except
any formatting using (m|k|sat)v1 ... (m|k|sat)v8 it gives me no output. Here is what I have tested on Ubuntu 20.04, would love to reduce the decimal places at the moment I'm using FORMAT: {raw} {b} successfully. 

Format {(m|k|sat)v8} {b} 
Provider Coinbase
base XBY
Quote AUD   

I copied and pasted the format from the code below to ensure it is using the exact same characters.
  ['(m|k|sat)v8', _('formatted value with 8 decimals')],

**Comment by OttoAllmendinger** [comment]
just to check: `{mv0}` does not display anything for btc?

**Comment by bigmalloy** [comment]
{mv0} shows 75 for BTC but nothing for XBY

**Comment by OttoAllmendinger** [comment]
so `{mv0}` will show the value for 1/1000th BTC, with 0 decimals of precision

`{kv0}` will show the value of 1000 BTC with 0 decimals of precision

the prefix before the `v` is the multiplier and the suffix number is the precision

**Comment by bigmalloy** [comment]
Ahhh thanks I am using {v5} {b} and this is showing me xby value to 5 decimal places which is what I wanted thanks for your help
