### ISSUE TITLE
Gnome 41

### ISSUE THREAD

**Issue by MuXodious** [OttoAllmendinger/gnome-shell-bitcoin-markets#120]
Extension needs to be updated for Gnome 41. I managed to make it work on my Fedora 35 setup by adding `, "41"` to **metadata.json**. Thanks for the extension ^^

**Comment by iatmik** [comment]
where can i find the metadata.json file?

**Comment by cryptoquick** [comment]
@iatmik It's here if you want to make the change:
https://github.com/OttoAllmendinger/gnome-shell-bitcoin-markets/blob/master/src/metadata.json

I'm not the maintainer, and I'm not sure how responsive they'll be, but post a link to your fork and I'll use yours :)

**Comment by cryptoquick** [comment]
Also, I just noticed, you may want to make the change to this branch:
https://github.com/OttoAllmendinger/gnome-shell-bitcoin-markets/tree/gnome40

**Comment by cryptoquick** [comment]
damn I suck, looks like #122 has what we need

**Comment by cryptoquick** [comment]
couldn't figure it out, so I just sent @OttoAllmendinger some Bitcoin instead of spending more time on this

**Comment by iatmik** [comment]
Hi, thanks for the pathway. But my question is do I just add 3.41 like so?

  "shell-version": ["3.32", "3.34", "3.36", "3.38","3.41"],

regards,
iatmik

**Comment by iatmik** [comment]
or likeso
{
  "shell-version": ["3.32", "3.34", "3.36", "3.38","3.41"],
  "shell-version": ["40", "41"],
  "uuid": "bitcoin-markets@ottoallmendinger.github.com",
  "name": "Bitcoin Markets",
  "url": "https://github.com/OttoAllmendinger/gnome-shell-bitcoin-markets/",
  "description": "Display info on various crypto-currency exchanges.",
  "settings-schema": "org.gnome.shell.extensions.bitcoin-markets",
  "gettext-domain": "gnome-shell-bitcoin-markets",
  "git-version": "_gitversion_"
}

**Comment by iatmik** [comment]
Hi, looks like Otto updated this for 41.........all is in working order...thanks Otto.......

regards,
iatmik

**Comment by iatmik** [comment]
Hi Hunter, I made a mistake....Otto did not update this for GNOME 41....
my edit of the metadata.json worked....thanks for showing me the pathway via src file

just go into the metadat.json file using vim and edit as per above..

**Comment by cryptoquick** [comment]
Oh gotcha :/
Yeah, I reached out, haven't heard from him yet
I haven't had the time to deal with this either
But thanks for letting me know :)

**Comment by MuXodious** [comment]
You can simply download the latest compiled extension for Gnome 40 from [https://extensions.gnome.org/extension/648/bitcoin-markets/](url) here, unzip, edit metadata.json accordingly, zip it again, and install it via terminal using "gnome-extensions install EXTENSION.ZIP" command. 

It should look like this: 
`{
  "_generated": "Generated by SweetTooth, do not edit",
  "description": "Display info on various crypto-currency exchanges.",
  "gettext-domain": "gnome-shell-bitcoin-markets",
  "git-version": "v58",
  "name": "Bitcoin Markets",
  "settings-schema": "org.gnome.shell.extensions.bitcoin-markets",
  "shell-version": [
    "40",
    "41"
  ],
  "url": "https://github.com/OttoAllmendinger/gnome-shell-bitcoin-markets/",
  "uuid": "bitcoin-markets@ottoallmendinger.github.com",
  "version": 58
}`

Else you can compile it yourself, if you so choose. Download the "Gnome 40" branch, edit the metadata.json file located under ".../gnome40/src/", and compile following the instructions given on README.md. 

Changes to metadata.json should look like this in this instance: 
`{
  "shell-version": ["40", "41"],
  "uuid": "bitcoin-markets@ottoallmendinger.github.com",
  "name": "Bitcoin Markets",
  "url": "https://github.com/OttoAllmendinger/gnome-shell-bitcoin-markets/",
  "description": "Display info on various crypto-currency exchanges.",
  "settings-schema": "org.gnome.shell.extensions.bitcoin-markets",
  "gettext-domain": "gnome-shell-bitcoin-markets",
  "git-version": "_gitversion_"
}`

Personally, I used the first method.

**Comment by iatmik** [comment]
Hey Otto, 

vielen Dank....

regards,
iatmik

**Comment by cryptoquick** [comment]
@MuXodious Awesome! Your instructions worked, thank you. I had to uninstall the extension and restart my shell to get it working again, but all is good now.

**Comment by OttoAllmendinger** [comment]
Gnome 41 version is pending review in the store

**Comment by MuXodious** [comment]
Thank you @OttoAllmendinger ❤️

**Comment by cryptoquick** [comment]
Thanks @OttoAllmendinger!

**Comment by Strykar** [comment]
I uninstalled it and it won't install via the Gnome extensions site, just sits there after I toggle enable, does not offer to download.

**Comment by OttoAllmendinger** [comment]
@Strykar you may have to log out and log back in again

**Comment by Strykar** [comment]
@OttoAllmendinger Thanks, it shows "Incompatible" on the extension page after logging out, perhaps I just need to wait for the updated version to be approved?

**Comment by OttoAllmendinger** [comment]
I actually just inactivated it as a result of bug #125. I will post an update here once the fixed version is pending review.

**Comment by OttoAllmendinger** [comment]
fixed version is available in the extension store

**Comment by Strykar** [comment]
@OttoAllmendinger Thanks, but it won't install, it won't offer to download. I've tried logging out and back in, weird.
