### ISSUE TITLE
Keeps crashing since yesterday's update

### ISSUE THREAD

**Issue by Razer0123** [OttoAllmendinger/gnome-shell-bitcoin-markets#125]
The extensions crashes and makes Gnome restart every 1 min or so after yesterday's update

Not sure how to post a log of the issue

**Comment by OttoAllmendinger** [comment]
I am actually observing this as well, thanks for confirming

**Comment by OttoAllmendinger** [comment]
fixed version is active in the extension store

**Comment by n1kcha** [comment]
now not working on gnome 40/fedora 34

**Comment by OttoAllmendinger** [comment]
@n1kcha does this command have any relevant logs?

```
journalctl --user /usr/bin/gnome-shell -f 
```

**Comment by mbombonato** [comment]
After running the command above on Gnome 40/Ubuntu I've got the following errors:

```
Usage of object.actor is deprecated for MarketIndicatorView
get@resource:///org/gnome/shell/ui/environment.js:317:29
_initLayout@/home/user/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/extension.js:2197:13
_init@/home/user/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/extension.js:2170:18
_updateIndicators/indicators<@/home/user/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/extension.js:2349:28
_updateIndicators@/home/user/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/extension.js:2348:47
tryUpdateIndicators@/home/user/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/extension.js:2284:26
IndicatorCollection@/home/user/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/extension.js:2291:13
enable@/home/user/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/extension.js:2374:36
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:168:32
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:351:26
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:241:39
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13
```



```
JS ERROR: TypeError: _ is not a function
_initLayout@/home/user/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/extension.js:2203:67
_init@/home/user/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/extension.js:2170:18
_updateIndicators/indicators<@/home/user/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/extension.js:2349:28
_updateIndicators@/home/user/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/extension.js:2348:47
tryUpdateIndicators@/home/user/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/extension.js:2284:26
IndicatorCollection@/home/user/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/extension.js:2291:13
enable@/home/user/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/extension.js:2374:36
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:168:32
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:351:26
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:241:39
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13
```

**Comment by mbombonato** [comment]
Also, here's a screenshot of the Settings window. Totally broken after the last update.

![image](https://user-images.githubusercontent.com/38539268/142857631-86cbdf3a-7ca7-4117-ba6a-9c1e2a637450.png)

**Comment by n1kcha** [comment]
JS ERROR: TypeError: _ is not a function
                                                    _initLayout@/home/nikos/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/extension.js:2203:67
                                                    _init@/home/nikos/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/extension.js:2170:18
                                                    _updateIndicators/indicators<@/home/nikos/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/extension.js:2349:28
                                                    _updateIndicators@/home/nikos/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/extension.js:2348:47
                                                    tryUpdateIndicators@/home/nikos/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/extension.js:2284:26
                                                    IndicatorCollection@/home/nikos/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/extension.js:2291:13
                                                    enable@/home/nikos/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/extension.js:2374:36
                                                    _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
                                                    _onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:493:35
                                                    _onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:493:14
                                                    createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:516:46
                                                    enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:194:29
                                                    EnableExtension@resource:///org/gnome/shell/ui/shellDBus.js:311:38
                                                    _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:310:38
                                                    _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:387:34

**Comment by str** [comment]
I was able to make it work editing the file `~/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/extension.js`  at line 2203

replace
```
this._popupItemSettings = new PopupMenu.PopupMenuItem(_('Settings'));
```

with
```
this._popupItemSettings = new PopupMenu.PopupMenuItem('Settings');
```

and then restart gnome (alt+F2,  type r + [enter])
