### ISSUE TITLE
How to track Moscow Time (BTC sats per US dollar)

### ISSUE THREAD

**Issue by csmosx** [OttoAllmendinger/gnome-shell-bitcoin-markets#129]
This is more of an FYI to those interested.

To get a USD/BTC pair, the only working Providers currently seems to be `CryptoCompare` and `Coinbase`.
Base: `USD`
Quote: `BTC`
Format: `{satv0}`

Would prefer to have no comma, but no big deal.

![Screenshot](https://user-images.githubusercontent.com/100840/149818580-0a53bc79-cf92-4c22-ae6c-b8e473a493fb.png)

**Comment by OttoAllmendinger** [comment]
I actually added first-class support for this :) 
![image](https://user-images.githubusercontent.com/283533/150425935-2ae06bf5-550d-4e9d-9bdc-f259bdaa8232.png)

**Comment by cryptoquick** [comment]
Thank you for this! I'm now living on Moscow time. I'm using this symbol: ṩ
