### ISSUE TITLE
Can't install/upgrade

### ISSUE THREAD

**Issue by csmosx** [OttoAllmendinger/gnome-shell-bitcoin-markets#130]
Tried to upgrade to latest version via `extensions.gnome.org` but get a non-descript ERROR button.

Uninstalled and tried to reinstall, same problem.

Not sure how to debug such an error.
![Screenshot from 2022-01-21 09-38-03](https://user-images.githubusercontent.com/100840/150555742-0eac7be2-c92b-4e9c-afcd-48d2d7d15257.png)

**Comment by OttoAllmendinger** [comment]
please log out and log back in again

**Comment by csmosx** [comment]
Hey that worked! Thanks.
![](https://media.giphy.com/media/FspLvJQlQACXu/giphy.gif)
