### ISSUE TITLE
Gnome 42 Support

### ISSUE THREAD

**Issue by MuXodious** [OttoAllmendinger/gnome-shell-bitcoin-markets#133]
Hello, Otto! Thank you again for the extension. I have just upgraded to Gnome 42 and tried a simple edit (adding "42") to metadata.json, and I can say that the extension is broken on Gnome 42, unfortunately. At first it appears to be working, if you had it installed previously, untill you enter the extension settings.

Side panel for changing entries is basically gone. Upon adding a new entry side panel comes up, but only the new entry is editable. Older entries gets removed. Also, extension only shows up on the top bar after restarting the Gnome Shell. I'm adding more screenshots in order of action. 

 1.
![Screenshot from 2022-04-08 13-43-40](https://user-images.githubusercontent.com/64381665/162421537-34932b23-768b-42ec-a247-948ec5569555.png)

2.
![Screenshot from 2022-04-08 13-44-33](https://user-images.githubusercontent.com/64381665/162421553-e6c0eea3-55db-41f7-8aff-0c6580552a6d.png)

3.
![Screenshot from 2022-04-08 13-45-06](https://user-images.githubusercontent.com/64381665/162421576-a1cd3fcd-8ad0-4715-be2c-cb3b6b628a9b.png)

4.
![Screenshot from 2022-04-08 13-45-14](https://user-images.githubusercontent.com/64381665/162421607-8d5cb4db-25af-491f-bbb7-dd43a6fee4e0.png)

I hope this helps. Let me know, if you need logs or testing. Thanks!

**Comment by alex-tee** [comment]
+1 the extension broke after I upgraded my system to gnome 42

**Comment by OttoAllmendinger** [comment]
I'll try to fix it this weekend

**Comment by Kwaskoff** [comment]
> I'll try to fix it this weekend

All users of Ubuntu 21.10 must upgrade to Ubuntu with Gnome 42 before July 14, 2022. If you will have time to do fix before this date - it will be nice!

**Comment by OttoAllmendinger** [comment]
already fixed :)
