### ISSUE TITLE
Gnome 43.beta: TyperError: Soup.SessionAsync is not a constructor

### ISSUE THREAD

**Issue by yellowgh0st** [OttoAllmendinger/gnome-shell-bitcoin-markets#136]
![Screenshot from 2022-08-31 22-29-58](https://user-images.githubusercontent.com/34014106/187776128-481c469f-68a4-4c79-83e3-40db684cd571.png)

**Comment by nssy** [comment]
Have the same issue.
Guess libsoup was updated from 2.4 to 3.0

**Comment by Razer0123** [comment]
Same problem on Fedora 37 with Gnome 43

**Comment by Razer0123** [comment]
No update yet?:(

**Comment by Razer0123** [comment]
Can we users do anything? this extension is vital to me

**Comment by Razer0123** [comment]
> Have the same issue. Guess libsoup was updated from 2.4 to 3.0

Any idea on a workaround? would using the old libsoup fix it?

**Comment by OttoAllmendinger** [comment]
I will fix it this weekend

**Comment by azuledu** [comment]
Hi @OttoAllmendinger, 
Maybe this can help with the fix:

https://github.com/sereneblue/gnome-shell-extension-krypto/commit/772579880b220ee51d8a1b25a25dd74c29c548dc

**Comment by OttoAllmendinger** [comment]
sorry I was too optimistic... this is going to take longer

**Comment by Razer0123** [comment]
> sorry I was too optimistic... this is going to take longer

Any ETA?

**Comment by OttoAllmendinger** [comment]
master branch has Gnome43 support

new version is pending review in extensions.gnome.org

**Comment by nssy** [comment]
Now working perfectly on Gnome 43  :heavy_check_mark: 
Have just updated it from extensions.gnome.org.
Thanks for the update... :tada:
