### ISSUE TITLE
GNOME 46 Support

### ISSUE THREAD

**Issue by kallisti5** [OttoAllmendinger/gnome-shell-bitcoin-markets#153]
GNOME 46 is out, and it broke again :-)

**Comment by molitona** [comment]
@OttoAllmendinger

**Comment by stonedbear** [comment]
It is such a pain in the ass for the maintainers that every time gnome updates, extensions break... #rantover

**Comment by molitona** [comment]
> It is such a pain in the ass for the maintainers that every time gnome updates, extensions break... #rantover

yep indeed and we loose very useful things...

**Comment by kallisti5** [comment]
100% agree.   I honestly think I preferred the maintainers of Gnome 2 :laughing:    The Gnome 3 folks don't seem to care.

**Comment by davidjao** [comment]
I got it working in Gnome 46.

Patch attached.
[bitcoin-markets-gnome46.patch.txt](https://github.com/OttoAllmendinger/gnome-shell-bitcoin-markets/files/14920968/bitcoin-markets-gnome46.patch.txt)

**Comment by molitona** [comment]
> I got it working in Gnome 46.
> 
> Patch attached. [bitcoin-markets-gnome46.patch.txt](https://github.com/OttoAllmendinger/gnome-shell-bitcoin-markets/files/14920968/bitcoin-markets-gnome46.patch.txt)

thanks @davidjao 

it's just replacing add_actor method by add_child and it should works

```
layout.add_actor(this._statusView);
layout.add_actor(this._indicatorView);
this.add_actor(layout);
```
to become

```
layout.add_child(this._statusView);
layout.add_child(this._indicatorView);
this.add_child(layout);
```

almost all extensions are broken cause of this https://github.com/bmwiedemann/openSUSE/blob/13c1179cab4f21925e453e039e04d9174e286d7a/packages/h/hamster-time-tracker/0174-Fix-compatibility-issues-with-Gnome-shell-46.patch#L4

**Comment by OttoAllmendinger** [comment]
Thanks for the hint, just merged the fix on `master` and uploaded new version on e.g.o

**Comment by davidjao** [comment]
I see the new version on extensions.gnome.org but I don't see any new commits to `master`, am I missing something?

**Comment by OttoAllmendinger** [comment]
> I see the new version on extensions.gnome.org but I don't see any new commits to `master`, am I missing something?

no, I just forgot to push :see_no_evil:
