### ISSUE TITLE
Add Support for Ether (Ethereum)

### ISSUE THREAD

**Issue by paluka** [OttoAllmendinger/gnome-shell-bitcoin-markets#22]
Hi, 
Thank you for making this Gnome Extension. It is great.
Can you add support for Ether from Ethereum? It has around 1 billion dollar market capitalization (# 2 after Bitcoin).

I would greatly appreciate it!
Thanks,
Erik

**Comment by Ghedeon** [comment]
+1, would be a perfect fit for this extension. UI wise, looks already extendable enough to adopt other currencies.

**Comment by stejoo** [comment]
+1, would like to have more coins in it as well. ETH would be a good start.

**Comment by groundhog0** [comment]
+1 ,ethereum zcash and monero

**Comment by OttoAllmendinger** [comment]
I would accept a good PR that adds support for this, but personally I don't have the time or motivation to do it myself.

**Comment by filidorwiese** [comment]
I've added PR #30

**Comment by OttoAllmendinger** [comment]
Altcoin support added by #30
