### ISSUE TITLE
Error getting values

### ISSUE THREAD

**Issue by Bunker** [OttoAllmendinger/gnome-shell-bitcoin-markets#23]
Whenever I try to show the current Bitcoin value in Euro from a specific exchange, it shows error instead of the value. However when I use Average instead of a specific exchange I get the average value. 

Specs.:

OS and DE: Antergos (arch linux) with Gnome 3.20.2 on X11
extension settings:
    - Unit: BTC or mBTC
    - Decimals: Default
    - Show change: on
    - Provider: BitcoinAverage
    - Currency: EUR
    - Average: OFF
    - Exchange: all with EUR

**Comment by OttoAllmendinger** [comment]
Which extension version are you using? http://extensions.gnome.org or the master branch version? 

I can't reproduce it on the master branch. 

![image](https://cloud.githubusercontent.com/assets/283533/18464819/a726007e-7993-11e6-8fb8-85aa694135df.png)

Unfortunately there is a bug where settings are not applied instantly, sometimes you have to change them back and four

**Comment by Bunker** [comment]
I use the extensions.gnome.org and it used to work until 3 days ago.

**Comment by Bunker** [comment]
after several reboots over the last days, this morning it started working again. 

I'll keep monitoring it, if it happens again, I'll report in again.

Is there anything specific in the log files I have to look for, if this happens again?

**Comment by OttoAllmendinger** [comment]
It should be logged here: https://github.com/OttoAllmendinger/gnome-shell-bitcoin-markets/blob/master/src/extension.js#L117 (prefixed with "err")

Please reopen this issue when it comes up again. 

I added issue #24 to address the problem of getting error messages.
