### ISSUE TITLE
EUR/BTC currency pair support for Bitstamp

### ISSUE THREAD

**Issue by fturco** [OttoAllmendinger/gnome-shell-bitcoin-markets#28]
Currently if I select the Bitstamp exchange I can only use the USD/BTC currency pair. What about adding EUR/BTC currency pair as an additional option? It seems the [Bitstamp API](https://www.bitstamp.net/api/) provides that value.

**Comment by OttoAllmendinger** [comment]
Done, thanks for the hint. Be aware that it will take a while until the update is approved extensions.gnome.org.
