### ISSUE TITLE
How to reduce space between prices in taskbar?

### ISSUE THREAD

**Issue by soamaven** [OttoAllmendinger/gnome-shell-bitcoin-markets#34]
What should I change to reduce the space between the prices? I tried stylesheet.css, and that helped a bit, but Id like them much close because there are too many things on my task bar.

**Comment by OttoAllmendinger** [comment]
You can save a bit of space by dropping the space reserved for the status indicator. Change line 82 in extension.js to:

```
     // layout.add_actor(this._statusView);
```

**Comment by OttoAllmendinger** [comment]
newest version doesn't show blank space when change indicator is missing
