### ISSUE TITLE
Other currencies(e.g. ETH)?

### ISSUE THREAD

**Issue by olanod** [OttoAllmendinger/gnome-shell-bitcoin-markets#38]
It would be nice if I can use the same extension to track different currencies prices :)

**Comment by KonradIT** [comment]
Such as Bitcoin Cash.

**Comment by OttoAllmendinger** [comment]
I will try to fix the bugs currently preventing this by the end of the month.

**Comment by 256k** [comment]
would be great to be able to decide which coins to follow. or at least have an explanation of where to edit the files to add our own APIs?

**Comment by OttoAllmendinger** [comment]
Master branch should work now. Poloniex has the most alts. If some are missing, please add them to the `ProviderFoo.js` and submit a PR.
