### ISSUE TITLE
Can't change settings

### ISSUE THREAD

**Issue by victorperin** [OttoAllmendinger/gnome-shell-bitcoin-markets#40]
I'm using the new Ubuntu 17.10.

I installed the extension, I can see it on the menu, I can open the settings, but any button I click, there's no response.

**Comment by OttoAllmendinger** [comment]
This is a known bug, I have submitted a fix on extensions.gnome.org that is pending review. It is also fixed in the master branch.

**Comment by victorperin** [comment]
Thanks, I didn't noticed.
Anyway, i fixed changing the dconf object manually. :)
