### ISSUE TITLE
Request: Please add Bitfinex

### ISSUE THREAD

**Issue by str** [OttoAllmendinger/gnome-shell-bitcoin-markets#45]
Please add Bitfinex

**Comment by str** [comment]
I can't find EOS anywhere.

**Comment by samundra** [comment]
What is EOS?

**Comment by str** [comment]
https://eos.io/
https://coinmarketcap.com/currencies/eos/

**Comment by rawkode** [comment]
Would love this. Bitfinex or Binance support please
