### ISSUE TITLE
Dont works for several days

### ISSUE THREAD

**Issue by volandku** [OttoAllmendinger/gnome-shell-bitcoin-markets#53]
Hi.
It dont work now with any providers.
Only dots and nothing more ((

Even after update I did today nothing changes

**Comment by samundra** [comment]
Hi Sergey,

Please make sure that you have enough spaces on panel to display all the
digits. In my case I had 3 tickers and they didn't had enough spaces and
thus only showed dots instead of digits.

**Comment by volandku** [comment]
Yes. That`s it! Thanks!
Any options to move indicator to left?

**Comment by samundra** [comment]
@volandku 
I haven't come across any. Usually if you disable and enable the extension it should put it to the left for the current session. But next time when system boots, it will pick another position depending upon the order the extensions were loaded by the system.

**Comment by OttoAllmendinger** [comment]
The most recent version allows saving a little bit of space when disabling "show change". Other than that I think https://github.com/OttoAllmendinger/gnome-shell-bitcoin-markets/issues/29 can help.
