### ISSUE TITLE
Add Kraken as provider

### ISSUE THREAD

**Issue by eloo** [OttoAllmendinger/gnome-shell-bitcoin-markets#55]
Would be great if Kraken would be available as a provider.

I've tried it based on the other providers but it seems that i missed something.
There is no value displayed in the menu bar :/

Can some have a look and give me some hints?
Thanks

**Comment by eloo** [comment]
Okay got it working.
But the API of kraken is not that stable :P

**Comment by eloo** [comment]
@OttoAllmendinger i've just seen you have adapted/fixed my PR from yesterday. Thanks.
And yes the 10 second interval was only for testing. Please increase to your defaults (60s?)
Maybe the interval should be configerable?
Should I close my PR?

**Comment by OttoAllmendinger** [comment]
I'll close it for you ;) 

thanks for your work!
