### ISSUE TITLE
[Request] Add XVG (Verge) please ?

### ISSUE THREAD

**Issue by Tikilou** [OttoAllmendinger/gnome-shell-bitcoin-markets#57]
Hi, XVG is a confidential crypto currencie, more informations on : http://www.crypthor.net/understanding-verge-alias-the-monero-slayer/

We could find it on Binance, Bittrex, Cryptopia, Changelly...

Thanks :)

**Comment by OttoAllmendinger** [comment]
I will change it so that you can enter whatever symbol you want

**Comment by OttoAllmendinger** [comment]
base and quote currencies are now free-form text fields
