### ISSUE TITLE
How to know if I have the latest version?

### ISSUE THREAD

**Issue by str** [OttoAllmendinger/gnome-shell-bitcoin-markets#64]
I see in your README that  Bitfinex is already working BUT I don't see it

![bitcoin markets_017](https://user-images.githubusercontent.com/123817/35101877-b853757c-fc26-11e7-81a5-c16bc681b799.png)

I tried uninstalling it and installing it again without success.

Thank you.

**Comment by OttoAllmendinger** [comment]
Unfortunately extensions.gnome.org is lagging a bit behind with reviews.
You can either install from the repo or wait until the new version is
accepted on e.g.o

**Comment by str** [comment]
OK, that's what I did. After cloning and make install it, gnome shell told my there was an updated version and if I wanted to updated it. I did, and it rolled back to the version published in e.g.o.

I think it was because of https://extensions.gnome.org/extension/1166/extension-update-notifier/

**Comment by eloo** [comment]
it seems that the new version is still not yet online in gnome extensions :(

**Comment by OttoAllmendinger** [comment]
now it is :)

**Comment by eloo** [comment]
nice
