### ISSUE TITLE
Add EOS crypto ?

### ISSUE THREAD

**Issue by vincegre** [OttoAllmendinger/gnome-shell-bitcoin-markets#68]
Possible to add EOS crypto in it ? Thanks ;)

**Comment by filidorwiese** [comment]
EOS is part of my PR #66. Would be nice if it was merged. Locally I'm running it without any problems for quite some time now.

**Comment by OttoAllmendinger** [comment]
I will probably make base and quote currencies text fields

**Comment by OttoAllmendinger** [comment]
base and quote currencies are now free-form text fields
