### ISSUE TITLE
stock on USB

### ISSUE THREAD

**Issue by dragonhunter01** [OttoAllmendinger/gnome-shell-bitcoin-markets#69]
gnome-shell-ext[9486]: Some code accessed the property 'ConfigView' on the module 'ProviderBitcoinAveragePrefs'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.

**Comment by OttoAllmendinger** [comment]
fixed in TS version
