### ISSUE TITLE
BROKEN!

### ISSUE THREAD

**Issue by str** [OttoAllmendinger/gnome-shell-bitcoin-markets#70]
It's been completely broken for a week or 2 now.

![workspace 1_040](https://user-images.githubusercontent.com/123817/44225543-0eef8f00-a14b-11e8-86e6-ac65c0a16bbf.png)

**Comment by OttoAllmendinger** [comment]
Which provider is this?

**Comment by str** [comment]
Sorry, it's working now and I didn't do anything.
