### ISSUE TITLE
Stellar Lumens, Dogecoin, EOS and other currencies missing for Kraken

### ISSUE THREAD

**Issue by corebots** [OttoAllmendinger/gnome-shell-bitcoin-markets#72]
Hello and thank you for the nice extension. Please could you add the missing currencies from the Kraken Exchange? Especially missing Stellar Lumens (STR/XLM) and Dogecoin (XDG) since their impact on bitcoin rates last months appears to be significant.

**Comment by OttoAllmendinger** [comment]
I will probably change it so that base and quote currencies are plain

there are too many coins to keep track of

**Comment by corebots** [comment]
thanks for looking into it

**Comment by OttoAllmendinger** [comment]
base and quote are now text fields, you can enter whatever you want
