### ISSUE TITLE
allow BTC as main currency

### ISSUE THREAD

**Issue by corebots** [OttoAllmendinger/gnome-shell-bitcoin-markets#74]
Currently we can only select EUR or USD as base currency which doesn't allow the extension to show rates of coins to bitcoin. We can only see EUR/XRP and not BTC/XRP. Hi-season is approaching, this could be a really nice addition to monitoring all from the shell top bar. Thank you for the work.

**Comment by OttoAllmendinger** [comment]
good idea 

(I hope high season is approaching :smile:)

**Comment by corebots** [comment]
Thank you!

**Comment by OttoAllmendinger** [comment]
base and quote currencies are now free-form text fields on master

**Comment by corebots** [comment]
thank you!
