### ISSUE TITLE
It's different among 2 installs

### ISSUE THREAD

**Issue by NinjaTurtle007** [OttoAllmendinger/gnome-shell-bitcoin-markets#78]
I have it on Ubuntu 18.10 and Pop OS 18.10 (which is based on ubuntu 18.10 but with gnome 3.30.2 instead of 3.30.1)
On Ubuntu it has drop down menus to select the currencies
on Pop Os you have to actually write the currency shortcode
and because I have to write them, if i write the same values as the ones from the drop down menus on Ubuntu it shows error.

Why is it different among 2 different versions of Ubuntu?

**Comment by OttoAllmendinger** [comment]
please run this command on both machines and provide the output:

```
cat  ~/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/metadata.json
```
