### ISSUE TITLE
Latest Bitcoin Markets Update Causes Error

### ISSUE THREAD

**Issue by Extremed** [OttoAllmendinger/gnome-shell-bitcoin-markets#80]
The most recent update (around March 25, 2019) has caused this great Bitcoin Markets app to continually display "error".  I uninstalled and reinstalled - same thing.  I uninstalled and shut down the computer and then restarted and re-installed - same "error".  
PLEASE GO BACK TO THE PREVIOUS VERSION!
Thanks,
Extreme D

**Comment by mad2sm0key** [comment]
More specifically, the error comes from HTTP.js - getJSON.
`message.response_body not defined`

I logged the response and the call returns the expected result. If I comment out this check, everything works.
`if (!("response_body" in message)) {
   return reject(new Error(`GET ${url}: message.response_body not defined`));
}`

Not sure why this fails though.

**Comment by OttoAllmendinger** [comment]
which gnome version is this?

**Comment by Extremed** [comment]
Thanks,  here is the result of the terminal command:
apt list gnome-session-bin | grep gnome
gnome-session-bin/now 3.28.1-0ubuntu3 amd64 [installed,local]

Regards,
David

Visit [Signs From Heaven](http://www.signsfromheaven.org/breaking-news), Your one-stop news source for independent thinkers!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mad2sm0key** [comment]
Same gnome version for me.

**Comment by OttoAllmendinger** [comment]
Thanks!

fixed in master, e.g.o version pending review
