### ISSUE TITLE
Three points below the price indicator when windows are maximized

### ISSUE THREAD

**Issue by Zausl** [OttoAllmendinger/gnome-shell-bitcoin-markets#81]
I observe here a non-critical but somewhat disturbing bug.
If I maximize any window, suddenly three points below the 1000 digit are displayed under the Bitcoin rate display.
I suppose these three points shouldn't be here.
If no window is maximized, these three points are not visible.

I am using Ubuntu 18.04 LTS & Gnome.
![BTC-Indicator-Bug](https://user-images.githubusercontent.com/49657349/56159654-8836ce80-5fc5-11e9-9162-ffb89a68a8d3.png)
Aside from that, I thank you for your good work.

**Comment by OttoAllmendinger** [comment]
are you sure it is due to the extension? is it still there when you remove/disable the extension?

**Comment by Zausl** [comment]
Dear Otto,
I just did another ugrade where a lot of packages were updated. I suppose Ubuntu has backported some changes from Disko Dingo to 18.04 LTS. Anyway, the three points have now disappeared.
Nevertheless many thanks for the answer and many thanks for your good work.

**Comment by OttoAllmendinger** [comment]
sure thing!
