### ISSUE TITLE
add HitBTC

### ISSUE THREAD

**Issue by krungthe** [OttoAllmendinger/gnome-shell-bitcoin-markets#84]
Would it be possible to add hitBTC? I can try to copy and modify one of the other providers with data from https://api.hitbtc.com/

**Comment by krungthe** [comment]
I have created a src/ProviderHitBTC.js but I'm having problems trying to make it work.
[ProviderHitBTC.zip](https://github.com/OttoAllmendinger/gnome-shell-bitcoin-markets/files/3341785/ProviderHitBTC.zip)

**Comment by OttoAllmendinger** [comment]
thanks, I will take a look
