### ISSUE TITLE
First indicator stops working after open lock screen 

### ISSUE THREAD

**Issue by ghost** [OttoAllmendinger/gnome-shell-bitcoin-markets#90]
Case
1- Add 2 binance(it should be same provider) indicator.
2- Lock the screen.
3- Login again.
4- The indicator that added firstly stops working. 

![image](https://user-images.githubusercontent.com/11859288/68552005-5aaee800-0423-11ea-874d-d4078a5f1dc9.png)

Workaround
If you open extension settings, it continues working.
 
Operating System
Ubuntu 19.10

**Comment by OttoAllmendinger** [comment]
Strange, I cannot reproduce it. Can you give me the output of gnome-shell after you log back in again?

```
journalctl -f /usr/bin/gnome-shell 
```

Also the output of ```gnome-shell --version``` please

**Comment by drizztDo** [comment]
GNOME Shell 3.34.1


Output
---------
--JS ERROR: status_code=1 reason_phrase=Cancelled method=GET uri=https://api.binance.com/api/v3/ticker/price?symbol=BTCUSDT
     HTTPError@/home/zergun/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/HTTP.js:11:17
     getJSON/</<@/home/zergun/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/HTTP.js:101:25
     cancel@/home/zergun/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/HTTP.js:133:9
     fetch/<@/home/zergun/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/BaseProvider.js:35:9
     fetch@/home/zergun/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/BaseProvider.js:29:12
     wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
     updateUrl@/home/zergun/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/ApiService.js:221:7
     PollLoop/update/<@/home/zergun/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/ApiService.js:251:33
     update@/home/zergun/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/ApiService.js:251:7
     run@/home/zergun/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/ApiService.js:166:9
--JS ERROR: status_code=1 reason_phrase=Cancelled method=GET uri=https://api.binance.com/api/v3/ticker/price?symbol=BTCUSDT
     HTTPError@/home/zergun/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/HTTP.js:11:17
     getJSON/</<@/home/zergun/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/HTTP.js:101:25
     cancel@/home/zergun/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/HTTP.js:133:9
     fetch/<@/home/zergun/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/BaseProvider.js:35:9
     fetch@/home/zergun/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/BaseProvider.js:29:12
     wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
     updateUrl@/home/zergun/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/ApiService.js:221:7
     PollLoop/update/<@/home/zergun/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/ApiService.js:251:33
     update@/home/zergun/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/ApiService.js:251:7
     run@/home/zergun/.local/share/gnome-shell/extensions/bitcoin-markets@ottoallmendinger.github.com/ApiService.js:166:9

**Comment by drizztDo** [comment]
I deleted BaseProvider:35. It is working now. 
If I don't understand wrongly, purpose of the line is that close previously opened session. 
So nonsense to delete it.

**Comment by thanhnguyennguyen** [comment]
Thank @drizztDo

**Comment by dbunic** [comment]
The same was on Fedora 32 with Gnome 3.36.6
- I added 3 Bitstamp tickers: BTCUSD, BTCEUR and LTCEUR
- after login only first was showing current price while other 2 showed "error"
- I commented out line 35 in BaseProvider.js as is in comment @ghost - thank you!

```
34    if (this.pendingRequest) {
35      //this.pendingRequest.cancel();
36    }

```
... and now everything works as expected. My first thought was that initial requests are too fast and server replies with error. But it seems to be an error due to JS code.

Anyway thanks author for the excellent Gnome extension!

**Comment by Razer0123** [comment]
Thanks! Hope the dev can release a fix now :)

**Comment by DPTJKKVH** [comment]
@ghost @dbunic can one of you please create a pull request so @OttoAllmendinger  has to just merge it? Many thanks!

**Comment by OttoAllmendinger** [comment]
Thanks, I could finally replicate it.
