### ISSUE TITLE
403 error with bitcoinaverage

### ISSUE THREAD

**Issue by MatzFan** [OttoAllmendinger/gnome-shell-bitcoin-markets#96]
I am getting an error from the extension with the following settings
![btc](https://user-images.githubusercontent.com/3764715/73558847-e39a5600-444b-11ea-90e2-8c567e5ef7e9.png)
The error is reported as:

```
BitAvg/coinfloor BTC/GBP
status_code=403
reason-phrase=Forbidden
method=GET
uri=https://apiv2.bitcoinaverage.com/exchanges/coinfloor
```
`gnome-shell --version` = 3.28.4, Ubuntu 18.04

Changing both the exchange & provider lead to a similar result (403 error).

I note that bitcoinaverage.com API [docs](https://apiv2.bitcoinaverage.com/#errors) say 403 means "Forbidden -- Higher level API Keys required"

**Comment by ser** [comment]
BitcoinAverage is gone, they require mandatory payments now.

**Comment by OttoAllmendinger** [comment]
well on the bright side: they were a maintenance pain anyway ;)

is there any replacement with a similar api?

**Comment by MatzFan** [comment]
Not that I know of, perhaps best to just remove Bitcoinaverage.

Great shell extension BTW.

**Comment by OttoAllmendinger** [comment]
I removed it
