### ISSUE TITLE
Coingecko - Multiples coins

### ISSUE THREAD

**Issue by MetallianFR68** [OttoAllmendinger/gnome-shell-bitcoin-markets#98]
Hi,

This extensions is very useful !
I'm trying to get 3 coins from COINGECKO.
For example BTC, ETH and XMR

One can sync (not always the same), but the other two show "error"
status_code=1
reason_phrase=Cancelled

I suspect the problem is that all 3 coins are querying the API at the same time and coingecko only answers the first and ignore the 2 others because there's a limit in their API saying: one query per second.

If this is the problem, the 3 should not ask at the same second

What do you think ?

**Comment by Razer0123** [comment]
Getting the same with Kraken and others

**Comment by mgcuadrado** [comment]
Had the same error. The fix from dbunic in https://github.com/OttoAllmendinger/gnome-shell-bitcoin-markets/issues/90 worked.

**Comment by DPTJKKVH** [comment]
@MetallianFR68 @Razer0123 An update of the extension should be published soon. When this happened, can you please try adding multiple coins again and see if the issue is gone?

**Comment by OttoAllmendinger** [comment]
should work now
